

spring:
  application:
    name: hypocrisy-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
    gateway:
      routes:
        - id: hypocrisy-search
          uri: lb://hypocrisy-search
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1
        - id: hypocrisy-item
          uri: lb://hypocrisy-item
          predicates:
            - Path=/item/**
          filters:
            - StripPrefix=1
  main:
    allow-bean-definition-overriding: true
server:
  port: 8000